<a href="https://colab.research.google.com/github/braxtonowens/MATH510/blob/main/L8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [26]:
'''
Function to take QR factorization of an mxn matrix A where m>=n using modified Gram-schmidt orthonomalization
'''
def msg(A):
  m,n = np.shape(A)
  r = np.zeros((n,n))
  v = np.array(A)
  q = np.zeros((m,n))
  for i in range(n):
    r[i,i] = np.linalg.norm(v[:,i])
    q[:,i] = v[:,i]/r[i,i]
    for j in range(i+1,n):
      r[i,j]=np.dot(np.transpose(q[:,i]),v[:,j])
      v[:,j]=v[:,j]-r[i,j]*q[:,i]
  return (q,r)
  
    


In [29]:
A = [[1,2,3,7],[1,3,2,6],[3,2,1,5]]
q,r=msg(A)

In [30]:
print(A-np.dot(q,r))

[[ 0.          0.          0.43939394  1.45454545]
 [ 0.          0.         -0.39393939  0.45454545]
 [ 0.          0.         -0.34848485 -0.63636364]]
